
# - `gridsearch` ------------------------------------------------------------- #
# - function: grid plot ------------------------------------------------------ #

### note: this function
###       (a) takes the resulting data frame from `gridSearch` function,
###       (b) plots a heatmap that shows the distribution of model fits.

# PART 1: FUNCTION ----------------------------------------------------------- #

#' Plot Grid
#'
#' This function plots the distribution of error scores resulting from `gridSearch`.
#' @param data A data frame generated by `gridSearch`
#' @param method If `method = quantile`, the cuts are based on the quantile of the error distribution. If `method = normalized`, cuts are based on the normalized error scores (error / n), which ranges from 0 to 2, for `pattern = contingency`, or normalized KS statistics, which ranges from 0 to 1, for `pattern = slopes`.
#' @param qcut1 Cut 1 for the quantile method.
#' @param qcut2 Cut 2 for the quantile method.
#' @param qcut3 Cut 3 for the quantile method.
#' @param ncut1 Cut 1 for the normalized method.
#' @param ncut2 Cut 2 for the normalized method.
#' @param ncut3 Cut 3 for the normalized method.
#'
#' @return A `ggplot2` object.
#' @export
#'

gridPlot <-

  function(data,
           method = c("quantile", "normalized"),
           qcut1 = 0.05,
           qcut2 = 0.10,
           qcut3 = 0.20,
           ncut1 = 0.05,
           ncut2 = 0.10,
           ncut3 = 0.20) {

    method = match.arg(method)
    lvls <- paste("Group", 1:4)

    if (data |>
        dplyr::select(dplyr::any_of(c("rate", "strength", "direction", "error", "pattern", "n"))) |>
        ncol() != 6
    )
      stop("Error: One or more columns from `gridSearch` is missing.")

    ## organize data

    if (method == "quantile") {

      data <- data |>
        dplyr::mutate(
          group = dplyr::case_when(
            error <= stats::quantile(.data$error, qcut1, na.rm = TRUE) ~
              "Group 1",
            error <= stats::quantile(.data$error, qcut2, na.rm = TRUE) ~
              "Group 2",
            error <= stats::quantile(.data$error, qcut3, na.rm = TRUE) ~
              "Group 3",
            TRUE ~ "Group 4"
          )
        ) |>
        dplyr::mutate(group = factor(.data$group, levels = lvls))

    }

    if (method == "normalized") {

      if (unique(data$pattern) == "contingency") {
        data <- data |>
          dplyr::mutate(error = .data$error / .data$n) |>
          dplyr::mutate(
            group = dplyr::case_when(
              .data$error <= ncut1 ~ "Group 1",
              .data$error <= ncut2 ~ "Group 2",
              .data$error <= ncut3 ~ "Group 3",
              .default = "Group 4"
            )
          ) |>
          dplyr::mutate(group = factor(.data$group, levels = lvls))

      }

      if (unique(data$pattern) == "slopes") {
        data <- data |>
          dplyr::mutate(
            group = dplyr::case_when(
              .data$error <= ncut1 ~ "Group 1",
              .data$error <= ncut2 ~ "Group 2",
              .data$error <= ncut3 ~ "Group 3",
              .default = "Group 4"
            )
          ) |>
          dplyr::mutate(group = factor(.data$group, levels = lvls))

      }

    }

    ## facet design
    design <-
      c(
      "
      AABBCC
      #DDEE#
      ")

    ## plot
    plot <- data |>
      ggplot2::ggplot(ggplot2::aes(x = .data$rate, y = .data$strength)) +
      ggplot2::scale_x_continuous(limits = c(0, 1),
                                  labels = scales::label_percent()) +
      ggplot2::scale_y_continuous(limits = c(0, 2),
                                  labels = scales::pretty_breaks()) +
      ggplot2::labs(x = "Rate of Change", y = "Strength of Change") +
      hrbrthemes::theme_ipsum_rc(grid = "XY") +
      ggplot2::geom_point(ggplot2::aes(color = .data$group), size = 2) +
      ggplot2::scale_color_manual(
        values = c("#000000", "#bbbbbb", "#eeeeee", "transparent"), drop = FALSE
        ) +
      ggplot2::theme(legend.position = "none")

    ## design
    plot + ggh4x::facet_manual(~direction, design = design)

  }

# ---------------------------------------------------------------------------- #
