
# - `gridsearch` ------------------------------------------------------------- #
# - function: grid plot ------------------------------------------------------ #

### note: this function
###       (a) takes the resulting data frame from `gridSearch` function,
###       (b) plots posterior summary and conditional posteriors.

# PART 1: FUNCTION ----------------------------------------------------------- #

#' Plot DGP Parameters
#'
#' This function plots the distribution of accepted samples.
#' @param data A data frame generated by `gridSearch`.
#' @param plot If `posterior`, plots a density plot for each non-fixed parameter. If `conditional`, plots the accepted samples by different balance levels.
#' @param percent The percentage of samples to keep.
#'
#' @return A `ggplot2` object.
#' @export
#'

gridPlot <-

  function(data, plot = c("posterior", "conditional"), percent = 5) {

    plot = match.arg(plot)

    # --- prettify the parameters
    levels <- c("ic_sample", "pc_sample", "bal_sample", "rel_sample")
    labels <- c("Change Strength",
                "Change Rate",
                "Change Balance",
                "Response Reliability")

    # --- drop fixed parameters
    data <- as.data.frame(data)
    data <- data[, sapply(data, stats::sd) != 0]

    # --- keep samples closest to data
    data <- data |>
      dplyr::arrange(.data$error) |>
      dplyr::slice(1:nrow(data) * percent) |>
      dplyr::select(-.data$error)

    if (plot == "posterior") {

      p <- data |>
        tidyr::pivot_longer(cols = tidyr::everything(), names_to = "param") |>
        dplyr::mutate(param = factor(.data$param, levels = levels, labels = labels)) |>
        ggplot2::ggplot(ggplot2::aes(.data$value)) +
        ggplot2::geom_density() +
        ggplot2::facet_wrap( ~ param, scales = "free") +
        ggplot2::labs(title = "Posterior Density", x = "Parameter Value", y = "Density")

    }

    if (plot == "conditional") {

      p <- data |>
        dplyr::mutate(balance = paste("Balance", "\U2248", round(.data$bal_sample, 1))) |>
        ggplot2::ggplot(ggplot2::aes(.data$pc_sample,
                                     .data$ic_sample)) +
        ggplot2::geom_point() +
        ggplot2::facet_wrap(~ balance) +
        ggplot2::labs(x = "Rate of Change", y = "Strength of Change")


    }

    return(p)

  }

# ---------------------------------------------------------------------------- #
